[package]
name = "chick"
version = "0.1.0"
edition = "2021"

[dependencies]
hyperlight-host = "0.1"
hyperlight-common = "0.1"
axum = "0.6"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }